on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: juric1962/hello-world-composite-action@362cced60994f3c3f565425a863cf9dffa803bd2
        with:
          who-to-greet: 'Juric Demyanuk'
      - run: |
          echo random-number ${{ steps.foo.outputs.random-number }}                 # "$RANDOM_NUMBER"
          echo "repository variable : $vars.REPOSITORY_VAR"
        shell: bash
        if: ${{ github.event_name == 'push' }}
        
      #  env:
      #    RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
